# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Prisma
                                 A QGIS plugin
 Plugin para fazer caracterização de imóveis
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2021-09-29
        git sha              : $Format:%H$
        copyright            : (C) 2021 by Zago
        email                : guilherme.nascimento@economia.gov.br
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import geopandas as gpd

from qgis.core import QgsProject, QgsVectorLayer

from shapely.wkt import loads

from .pgtools import PgTools
import json
import numpy as np

class ShpTools():

    def __init__(self):
        pass

    def OverlayAnalisys(self, operation_data):
        self.operation_data = operation_data
        areas_shp = []

        # Leitura dos dados que serão utilizados para sobreposição de áreas
        input = gpd.read_file(self.operation_data['input'])
        input.to_crs(31982)

        # Cálculo do buffer de aproximação
        if 'aproximacao' in self.operation_data:
            input['geometry'] = input['geometry'].buffer(self.operation_data['aproximacao'])

        # Leitura de shapefiles com GeoPandas
        for shp in range(len(self.operation_data['shp'])):
            areas_shp.append(gpd.read_file(self.operation_data['shp'][shp]['diretorioLocal']))
            areas_shp[shp].to_crs(31982)

        # Comparação de sobreposição entre input e Shapefiles
        index = 0
        result_shp = input.copy()
        result_shp['sobreposicao'] = False
        for area in areas_shp:
            for indexArea, rowArea in area.iterrows():
                for indexInput, rowInput in input.iterrows():
                    result_shp.loc[indexInput, 'areaLote'] = rowInput['geometry'].area
                    result_shp.loc[indexInput, 'ctr_lat'] = rowInput['geometry'].centroid.y
                    result_shp.loc[indexInput, 'ctr_long'] = rowInput['geometry'].centroid.x

                    if(rowArea['geometry'].intersection(rowInput['geometry'])):
                        result_shp.loc[indexInput, self.operation_data['shp'][index]['nome']] = (rowArea['geometry'].intersection(rowInput['geometry'])).area
                        result_shp.loc[indexInput, 'sobreposicao'] = True
                        # result_shp.loc[indexInput, self.operation_data['shp'][index]['nome']] = rowArea.loc[[indexArea], 'geometry']
            index += 1


        # Configuração acesso banco de dados Postgis junto das camadas que serão utilizadas
        databases = []
        for db in self.operation_data['pg']:
            databases.append({'connection': PgTools(db['host'], db['porta'], db['db'], db['usuario'], db['senha']),
                              'layers': db['tabelasCamadas']})

        # Comparação de sobreposição entre input e Postgis
        areas_db = []
        layers_db = []
        for database in databases:
            for layer in database['layers']:
                layers_db.append({str(layer): gpd.GeoDataFrame.from_dict(database['connection'].CalculateIntersectGPD(input.to_dict(), layer,
                                                                         (str(input.crs)).replace('epsg:', '')))})

            areas_db.append(layers_db)

        index_db = 0
        index_layer = 0
        result_db = input.copy()
        result_db['sobreposicao'] = False
        for db in areas_db:
            for layer_db in db:
                layer_db = list(layer_db.values())[0]
                layer_db.geometry = layer_db['geometry'].apply(loads)
                for indexArea, rowArea in layer_db.iterrows():
                    for indexInput, rowInput in input.iterrows():
                        result_db.loc[indexInput, 'areaLote'] = rowInput['geometry'].area
                        result_db.loc[indexInput, 'ctr_lat'] = rowInput['geometry'].centroid.y
                        result_db.loc[indexInput, 'ctr_long'] = rowInput['geometry'].centroid.x

                        if (rowArea['geometry'].intersection(rowInput['geometry'])):
                            result_db.loc[indexInput, self.operation_data['pg'][index_db]['nomeFantasiaTabelasCamadas'][index_layer]] = (
                                rowArea['geometry'].intersection(rowInput['geometry'])).area
                            print((rowArea['geometry'].intersection(rowInput['geometry'])).area)
                            result_db.loc[indexInput, 'sobreposicao'] = True
                            # result_db.loc[indexInput, self.operation_data['pg'][index]['tabelasCamadas']] = rowArea.loc[[indexArea], 'geometry']

                index_layer += 1
            index_db += 1

        result = {'shp': result_shp.to_dict(), 'pg': result_db.to_dict(), 'input': input.to_dict(),
                  'areas_shp': areas_shp, 'areas_db': areas_db}

        return result








