# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Prisma
                                 A QGIS plugin
 Plugin para fazer caracterização de imóveis
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2021-09-29
        git sha              : $Format:%H$
        copyright            : (C) 2021 by Zago
        email                : guilherme.nascimento@economia.gov.br
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import geopandas as gpd

from ..databases.db_connection import DbConnection
from ..databases.shp_handle import ShpHandle

class OverlayAnalisys():

    def __init__(self):
        pass

    def OverlayAnalisys(self, operation_config):
        self.operation_config = operation_config
        shp_handle = ShpHandle()

        # Leitura do shapefile de input
        input = shp_handle.read_shp_input(self.operation_config['input'])

        # Cálculo do buffer de proximidade
        if 'aproximacao' in self.operation_config:
            input = shp_handle.add_input_approximation(input, self.operation_config['aproximacao'])

        # Leitura de shapefiles de comparação
        gdf_selected_shp = shp_handle.read_selected_shp(self.operation_config['shp'])

        # Comparação de sobreposição entre input e Shapefiles
        overlay_shp = self.analisys_shapefiles(input, gdf_selected_shp)

        # Configuração acesso banco de dados Postgis junto das camadas que serão utilizadas
        databases = []
        for db in self.operation_config['pg']:
            databases.append({'connection': DbConnection(db['host'], db['porta'], db['baseDeDados'], db['usuario'], db['senha']),
                              'layers': db['tabelasCamadas']})

        # Comparação de sobreposição entre input e Postgis
        gdf_selected_db = []
        for database in databases:
            layers_db = []
            for layer in database['layers']:
                layers_db.append(gpd.GeoDataFrame.from_dict(database['connection'].CalculateIntersectGPD(input.to_dict(), layer,
                                                                         (str(input.crs)).replace('epsg:', ''))))

            gdf_selected_db.append(layers_db)

        # Comparação de sobreposição entre input e bases de dados de banco de dados
        overlay_db = self.analysis_databases(input, gdf_selected_db)

        result = {'overlay_shp': overlay_shp, 'overlay_db': overlay_db, 'input': input,
                  'gdf_selected_shp': gdf_selected_shp, 'gdf_selected_db': gdf_selected_db}

        return result

    def analisys_shapefiles(self, input, gdf_selected_shp):
        index = 0
        overlay_shp = input.copy()
        # overlay_shp['sobreposicao'] = False
        for area in gdf_selected_shp:
            print(self.operation_config['shp'][index]['nome'])
            print(area.crs)
            overlay_shp[self.operation_config['shp'][index]['nome']] = False
            for indexArea, rowArea in area.iterrows():
                for indexInput, rowInput in input.iterrows():
                    # overlay_shp.loc[index_result, 'areaLote'] = rowInput['geometry'].area
                    # overlay_shp.loc[index_result, 'ctr_lat'] = rowInput['geometry'].centroid.y
                    # overlay_shp.loc[index_result, 'ctr_long'] = rowInput['geometry'].centroid.x

                    if (rowArea['geometry'].intersection(rowInput['geometry'])):
                        overlay_shp.loc[indexInput, self.operation_config['shp'][index]['nome']] = True
                        # overlay_shp.loc[index_result, 'sobreposicao'] = True
                        # overlay_shp.loc[indexInput, self.operation_config['shp'][index]['nome']] = rowArea.loc[[indexArea], 'geometry']
            index += 1
        return overlay_shp

    def analysis_databases(self, input, gdf_selected_db):
        index_db = 0
        overlay_db = input.copy()
        overlay_db['sobreposicao'] = False
        for db in gdf_selected_db:
            index_layer = 0
            for layer_db in db:
                layer_db.geometry = gpd.GeoSeries.from_wkt(layer_db['geometry'])
                for indexArea, rowArea in layer_db.iterrows():
                    for indexInput, rowInput in input.iterrows():
                        # overlay_db.loc[index_result, 'areaLote'] = rowInput['geometry'].area
                        # overlay_db.loc[index_result, 'ctr_lat'] = rowInput['geometry'].centroid.y
                        # overlay_db.loc[index_result, 'ctr_long'] = rowInput['geometry'].centroid.x

                        # print("index_db: ", index_db)
                        # print("index_layer: ", index_layer)
                        # print(self.operation_config['pg'][index_db]['nomeFantasiaTabelasCamadas'][index_layer])
                        if (rowArea['geometry'].intersection(rowInput['geometry'])):
                            overlay_db.loc[indexInput, self.operation_config['pg'][index_db]['nomeFantasiaTabelasCamadas'][
                                    index_layer]] = True
                            # overlay_db.loc[index_result, self.operation_config['pg'][index_db]['nomeFantasiaTabelasCamadas'][index_layer]] = (
                            #     rowArea['geometry'].intersection(rowInput['geometry'])).area
                            # overlay_db.loc[index_result, 'sobreposicao'] = True
                            # overlay_db.loc[indexInput, self.operation_config['pg'][index]['tabelasCamadas'][index_layer]] = rowArea.loc[[indexArea], 'geometry']

                index_layer += 1

            index_db += 1
        return overlay_db